# Generated by Django 3.2.7 on 2021-10-05 15:54

from django.db import migrations

import edd.fields


class Migration(migrations.Migration):

    dependencies = [
        ("load", "0003_defaultunit_measurementnametransform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurementnametransform",
            name="edd_type_name",
            field=edd.fields.VarCharField(
                help_text="Name of this Measurement Type in EDD.",
                verbose_name="EDD Measurement Type",
            ),
        ),
        migrations.AlterField(
            model_name="measurementnametransform",
            name="input_type_name",
            field=edd.fields.VarCharField(
                help_text="Name of this Measurement Type in input.",
                verbose_name="Input Measurement Type",
            ),
        ),
    ]
