# Generated by Django 4.2.7 on 2023-11-23 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("load", "0005_protocol_restore"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="categorylayout", unique_together=None),
        migrations.RemoveField(model_name="categorylayout", name="category"),
        migrations.RemoveField(model_name="categorylayout", name="layout"),
        migrations.AlterUniqueTogether(name="categoryprotocol", unique_together=None),
        migrations.RemoveField(model_name="categoryprotocol", name="category"),
        migrations.RemoveField(model_name="categoryprotocol", name="protocol"),
        migrations.AlterUniqueTogether(name="parsermapping", unique_together=None),
        migrations.RemoveField(model_name="parsermapping", name="layout"),
        migrations.DeleteModel(name="Category"),
        migrations.DeleteModel(name="CategoryLayout"),
        migrations.DeleteModel(name="CategoryProtocol"),
        migrations.DeleteModel(name="Layout"),
        migrations.DeleteModel(name="ParserMapping"),
    ]
