---
x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: 1m
x-deploy: &default-deploy
  update_config:
    failure_action: rollback
    order: start-first
    parallelism: 1
networks:
  backnet:
services:
  http:
    command: ["gunicorn"]
    deploy: *default-deploy
    healthcheck:
      test: ["CMD", "curl", "--fail", "-LSs", "http://localhost:8000/health/"]
      interval: 15s
      retries: 5
      start_period: 120s
      timeout: 5s
    image: jbei/edd-core:latest
    logging: *default-logging
    networks:
      - backnet
    volumes:
      - edd_attachments:/var/www/uploads
      - edd_staticfiles:/var/www/static
  worker:
    command: ["celery"]
    deploy: *default-deploy
    healthcheck:
      test: ["CMD", "celery", "-A", "edd", "--workdir", "/code", "inspect", "ping"]
      interval: 1m
      retries: 3
      start_period: 120s
      timeout: 20s
    image: jbei/edd-core:latest
    logging: *default-logging
    networks:
      - backnet
    volumes:
      - edd_attachments:/var/www/uploads
      - edd_staticfiles:/var/www/static
volumes:
  edd_attachments:
  edd_staticfiles:
