---
networks:
  backnet:
services:
  http:
    command:
      - gunicorn
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
        parallelism: 1
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - -LSs
        - http://localhost:8000/health/
      interval: 15s
      start_period: 120s
      timeout: 5s
      retries: 5
    image: jbei/edd-core:latest
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "5"
    networks:
      - backnet
    volumes:
      - edd_attachments:/var/www/uploads
      - edd_staticfiles:/var/www/static
  websocket:
    command:
      - daphne
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
        parallelism: 1
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - -LSs
        - http://localhost:8000/health/
      interval: 15s
      start_period: 120s
      timeout: 5s
      retries: 5
    image: jbei/edd-core:latest
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "5"
    networks:
      - backnet
    volumes:
      - edd_attachments:/var/www/uploads
      - edd_staticfiles:/var/www/static
  worker:
    command:
      - celery
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
        parallelism: 1
    environment:
      C_FORCE_ROOT: "true"
    healthcheck:
      test:
        - CMD
        - celery
        - inspect
        - ping
        - -A
        - edd
        - --workdir
        - /code
      interval: 1m
      start_period: 120s
      timeout: 20s
      retries: 3
    image: jbei/edd-core:latest
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "5"
    networks:
      - backnet
    volumes:
      - edd_attachments:/var/www/uploads
      - edd_staticfiles:/var/www/static
version: "3.7"
volumes:
  edd_attachments:
  edd_staticfiles:
