# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 18:29
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20150729_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='profile.UserProfile')),
            ],
            options={
                'db_table': 'profile_task',
            },
        ),
    ]
