# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-03 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.TextField(blank=True, null=True)),
                ('logo_file', models.ImageField(null=True, upload_to='uploads/')),
                ('flavicon_file', models.ImageField(default='/static/main/images/edd_letters.png', null=True, upload_to='uploads/')),
                ('style_sheet', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branding.Branding')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
    ]
