# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.TextField(blank=True, null=True)),
                ('logo_file', models.TextField(blank=True, null=True)),
                ('flavicon_file', models.TextField(blank=True, null=True)),
                ('style_sheets', models.TextField(blank=True, null=True)),
                ('sites', models.ManyToManyField(to='sites.Site')),
            ],
        ),
    ]
