# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='sites',
        ),
        migrations.AddField(
            model_name='branding',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branding',
            name='flavicon_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='style_sheets',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
