# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-03 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('branding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='flavicon_file',
        ),
        migrations.AddField(
            model_name='branding',
            name='favicon_file',
            field=models.ImageField(default='/static/main/images/edd_letters.png', null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='branding',
            name='sites',
            field=models.ManyToManyField(through='branding.Page', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo_file',
            field=models.ImageField(default='/static/main/images/edd_letters.png', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='branding',
            name='logo_name',
            field=models.TextField(default='EDD'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='style_sheet',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
