# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0004_remove_branding_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='branding',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
