# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0005_branding_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='is_active',
        ),
    ]
