# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0007_auto_20170302_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branding',
            old_name='style_sheets',
            new_name='style_sheet',
        ),
    ]
