# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0008_auto_20170302_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='flavicon_file',
            field=models.ImageField(default='/static/main/images/edd_letters.png', null=True, upload_to='uploads/'),
        ),
    ]
