# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0009_auto_20170302_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='Page',
        ),
    ]
