import environ
from django.urls import reverse
from django_redis import get_redis_connection
from pytest import fixture

from .. import models
from . import factory


@fixture(autouse=True, scope="session")
def use_testing_cache():
    """
    If the CACHE_TEST_URL environment is available, switch the cache / Redis
    backend to that URL.
    """
    env = environ.Env()
    if "CACHE_TEST_URL" in env.ENVIRON:
        # using alternative fixture value
        yield True
        # once all tests are done, connect to alternate cache and compact AOF
        redis = get_redis_connection("default")
        redis.bgrewriteaof()
    else:
        yield False


@fixture(autouse=True)
def clear_cache(settings, use_testing_cache):
    """
    Resets the Redis cache before and after a test. There is a small chance of
    collisions for cache keys between tests, that amplifies greatly when tests
    are run repeatedly. Clearing out everything, every time, eliminates any
    possibility of collisions not intended by the individual test.
    """
    if use_testing_cache:
        redis = get_redis_connection("default")
        redis.flushdb()


class StudySession:
    """
    Defines the basic records required to test viewing a Study. Provides a
    generated user, with configurable permission level to a generated study.
    """

    def __init__(self, permission_type=models.StudyPermission.READ):
        self.user = factory.UserFactory()
        self.study = factory.StudyFactory()
        self.study.userpermission_set.update_or_create(
            user=self.user,
            defaults={"permission_type": permission_type},
        )

    def url(self, name):
        return reverse(name, kwargs={"slug": self.study.slug})


@fixture
def readable_session(db):
    return StudySession()


@fixture
def writable_session(db):
    return StudySession(permission_type=models.StudyPermission.WRITE)


@fixture
def ice_linked_session(db, ice_users):
    session = StudySession(permission_type=models.StudyPermission.WRITE)
    # copy API token from one of the already-set-up ICE users
    api_link = ice_users["readonly"].profile.applinks.first()
    session.user.profile.applinks.create(
        apptype=api_link.apptype,
        comment="Generated by writable session test fixture",
        secret_id=api_link.secret_id,
        secret=api_link.api_token,
        sort_key=1,
        url=api_link.url,
    )
    return session
