# Generated by Django 3.2.11 on 2022-01-21 19:36

import django.db.models.deletion
from django.db import migrations, models

import edd.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="DescribeExampleSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        default="Default", help_text="Name for this example set"
                    ),
                ),
                (
                    "example_image_file",
                    models.ImageField(
                        help_text=(
                            "Image displayed on the study page as an example of file "
                            "metadata content"
                        ),
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "example_file",
                    edd.fields.FileField(
                        help_text=(
                            "Example description file available for download via study pages"
                        ),
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.site",
                    ),
                ),
            ],
            options={"unique_together": {("name", "site")}, },
        ),
    ]
