---
version: "3.7"
networks:
  proxynet: {}
volumes:
  edd_attachments: {}
  edd_staticfiles: {}
  nginx_certs: {}
  nginx_confd: {}
  nginx_vhost: {}
  nginx_webroot: {}
services:
  nginx:
    build: ./nginx/
    image: jbei/nginx:mainline
    init: true
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    networks:
      - proxynet
    volumes:
      - nginx_confd:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_webroot:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - edd_attachments:/usr/share/nginx/html/uploads:ro
      - edd_staticfiles:/usr/share/nginx/html/static:ro
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "5"
    ports:
      - "80:80"
      - "443:443"
  nginx-gen:
    build: ./nginx-gen/
    image: jbei/nginx-gen:latest
    command:
      - "-watch"
      - "-notify"
      - "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
      - "/etc/docker-gen/templates/nginx.tmpl"
      - "/etc/nginx/conf.d/default.conf"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true
    links:
      - nginx
    networks:
      - proxynet
    volumes:
      - nginx_confd:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_webroot:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "5"
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx
    networks:
      - proxynet
    volumes:
      - nginx_confd:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_webroot:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
    logging:
      driver: "json-file"
      options:
        max-size: 1m
        max-file: "5"
