# Generated by Django 4.0.6 on 2022-07-20 19:34

from django.db import migrations

import edd.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_edd_2_7"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=edd.fields.VarCharField(blank=True, null=True),
        ),
    ]
