# Generated by Django 2.0.10 on 2019-01-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profile", "0005_remove_hstore")]

    operations = [
        migrations.RemoveField(model_name="usertask", name="profile"),
        migrations.DeleteModel(name="UserTask"),
    ]
