# Generated by Django 2.2.10 on 2020-02-15 10:16

from django.db import migrations

import edd.fields


class Migration(migrations.Migration):

    dependencies = [("profile", "0006_remove_usertask")]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="institution_name",
            field=edd.fields.VarCharField(),
        ),
        migrations.AlterField(
            model_name="institutionid",
            name="identifier",
            field=edd.fields.VarCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="initials",
            field=edd.fields.VarCharField(blank=True, null=True),
        ),
    ]
