# Generated by Django 3.2.11 on 2022-01-19 01:59

from django.db import migrations

import edd.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_edd_2_7"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadatatype",
            name="description",
            field=edd.fields.VarCharField(
                blank=True, help_text="Description for this Metadata Type", null=True
            ),
        ),
    ]
