# Generated by Django 3.2.7 on 2021-10-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_defaultunit"),
    ]

    operations = [
        migrations.DeleteModel(name="DefaultUnit",),
    ]
