# Generated by Django 3.2.11 on 2022-02-24 18:35

from django.db import migrations

import edd.fields


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_carbonsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadatatype",
            name="description",
            field=edd.fields.VarCharField(
                blank=True, help_text="Description for this Metadata Type", null=True
            ),
        ),
    ]
