# Generated by Django 4.2.2 on 2023-06-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_protocol"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="metaboliteexchange",
            index=models.Index(
                fields=["sbml_template", "measurement_type"],
                name="measurement_sbml_te_8056a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metabolitespecies",
            index=models.Index(
                fields=["sbml_template", "measurement_type"],
                name="measurement_sbml_te_c37105_idx",
            ),
        ),
    ]
