# Generated by Django 4.2.9 on 2024-04-01 21:51

from django.db import migrations

import edd.fields


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_django_42_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proteinidentifier",
            name="accession_code",
            field=edd.fields.VarCharField(
                blank=True,
                help_text="Required portion of Accession ID for easier lookup.",
                null=True,
                unique=True,
                verbose_name="Accession Code",
            ),
        ),
    ]
