# Generated by Django 4.2.9 on 2024-04-08 21:30

from django.db import migrations

import edd.fields


def switch_type_group(apps, schema_editor):
    MeasurementType = apps.get_model("main", "MeasurementType")
    MeasurementType.objects.filter(type_group="h").update(type_group="_")


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_proteinidentifier_accession_code"),
    ]

    operations = [
        migrations.RunPython(
            code=switch_type_group,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="type_group",
            field=edd.fields.VarCharField(
                choices=[
                    ("_", "Generic"),
                    ("m", "Metabolite"),
                    ("g", "Gene Identifier"),
                    ("p", "Protein Identifier"),
                ],
                default="_",
                help_text="Class of data for this Measurement Type.",
                verbose_name="Type Group",
            ),
        ),
        migrations.AlterField(
            model_name="measurementunit",
            name="type_group",
            field=edd.fields.VarCharField(
                choices=[
                    ("_", "Generic"),
                    ("m", "Metabolite"),
                    ("g", "Gene Identifier"),
                    ("p", "Protein Identifier"),
                ],
                default="_",
                help_text="Type of measurement for which this unit is used.",
                verbose_name="Group",
            ),
        ),
        migrations.DeleteModel(
            name="Phosphor",
        ),
    ]
