# Generated by Django 5.0.8 on 2024-09-27 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_strain"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metaboliteexchange",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="metaboliteexchange",
            name="measurement_type",
        ),
        migrations.RemoveField(
            model_name="metaboliteexchange",
            name="sbml_template",
        ),
        migrations.AlterUniqueTogether(
            name="metabolitespecies",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="metabolitespecies",
            name="measurement_type",
        ),
        migrations.RemoveField(
            model_name="metabolitespecies",
            name="sbml_template",
        ),
        migrations.RemoveField(
            model_name="sbmltemplate",
            name="object_ref",
        ),
        migrations.RemoveField(
            model_name="sbmltemplate",
            name="sbml_file",
        ),
        migrations.RemoveField(
            model_name="study",
            name="metabolic_map",
        ),
        migrations.RemoveIndex(
            model_name="protocol",
            name="main_protoc_sbml_ca_7d7196_idx",
        ),
        migrations.RemoveField(
            model_name="measurementtype",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="protocol",
            name="sbml_category",
        ),
        migrations.DeleteModel(
            name="MetaboliteExchange",
        ),
        migrations.DeleteModel(
            name="MetaboliteSpecies",
        ),
        migrations.DeleteModel(
            name="SBMLTemplate",
        ),
    ]
