# Generated by Django 2.0.3 on 2018-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("main", "0010_remove_line_replicate")]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="categorization",
            field=models.CharField(
                choices=[
                    ("NA", "None"),
                    ("OD", "Optical Density"),
                    ("HPLC", "HPLC"),
                    ("LCMS", "LCMS"),
                    ("RAMOS", "RAMOS"),
                    ("TPOMICS", "Transcriptomics / Proteomics"),
                ],
                default="NA",
                help_text="SBML category for this Protocol.",
                max_length=8,
                verbose_name="SBML Category",
            ),
        )
    ]
