# Generated by Django 2.0.8 on 2018-09-05 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0012_jsonb-metadata")]

    operations = [
        migrations.RemoveField(model_name="eddobject", name="meta_store"),
        migrations.RemoveField(model_name="measurement", name="meta_store"),
    ]
