# Generated by Django 2.0.13 on 2019-04-17 19:07

import django.db.models.deletion
from django.db import migrations, models

import edd.fields


class Migration(migrations.Migration):

    dependencies = [("main", "0017_carbon-src")]

    operations = [
        migrations.AddField(
            model_name="measurementtype",
            name="provisional",
            field=models.BooleanField(
                default=False,
                help_text="Flag indicating if the type is pending lookup in external Datasource",
                verbose_name="Provisional",
            ),
        ),
        migrations.AddField(
            model_name="metabolitespecies",
            name="short_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short code used for a species in the model.",
                max_length=255,
                null=True,
                verbose_name="Short Code",
            ),
        ),
        migrations.AddField(
            model_name="proteinidentifier",
            name="accession_code",
            field=edd.fields.VarCharField(
                blank=True,
                help_text="Required portion of Accession ID for easier lookup.",
                null=True,
                verbose_name="Accession Code",
            ),
        ),
        migrations.AlterField(
            model_name="measurementtype",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="(DEPRECATED) Short name used in SBML output.",
                max_length=255,
                null=True,
                verbose_name="Short Name",
            ),
        ),
        migrations.AlterField(
            model_name="metabolitespecies",
            name="measurement_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Mesurement type linked to this species in the model.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.MeasurementType",
                verbose_name="Measurement Type",
            ),
        ),
        migrations.AlterField(
            model_name="metabolitespecies",
            name="sbml_template",
            field=models.ForeignKey(
                help_text="The SBML Model defining this species link to a Measurement Type.",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.SBMLTemplate",
                verbose_name="SBML Model",
            ),
        ),
    ]
