[tool.coverage.run]
branch = true
source = [
    ".",
]

[tool.coverage.report]
omit = [
    "*test*",
    "*/commands/*",
    "*/migrations/*",
    "edd/settings/*",
    "manage.py",
]
exclude_also = [
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG:",
    "if (?:typing.)?TYPE_CHECKING:",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "^\\s*\\.\\.\\.$"
]

[tool.pytest.ini_options]
addopts = "--durations=10"
asyncio_mode = "auto"
DJANGO_SETTINGS_MODULE = "edd.settings.test"
filterwarnings = [
    # all warnings emitted only once per call location
    "default",
    # ignore OpenPyXL warnings about unsupported (cell value) extensions
    "ignore:Unknown extension is not supported and will be removed:UserWarning",
]
markers = [
    "ice_integration: tests integrating with ICE",
]
python_files = "test.py tests.py test_*.py *_tests.py"
