# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-02 14:15
# flake8: noqa

import django.contrib.postgres.fields
from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_edd-data-bootstrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtype',
            name='alt_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=main.models.fields.VarCharField(), blank=True, default=list, help_text='Alternate names for this Measurement Type.', size=None, verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='id_map',
            field=django.contrib.postgres.fields.ArrayField(base_field=main.models.fields.VarCharField(), default=list, help_text='List of identifiers mapping to external chemical datasets.', size=None, verbose_name='External IDs'),
        ),
        migrations.AddField(
            model_name='metabolite',
            name='smiles',
            field=main.models.fields.VarCharField(blank=True, help_text='SMILES string defining molecular structure.', null=True, verbose_name='SMILES'),
        ),
        migrations.AlterField(
            model_name='metabolite',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=main.models.fields.VarCharField(), default=list, help_text='List of tags for classifying this molecule.', size=None, verbose_name='Tags'),
        ),
    ]
