# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-13 23:43
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_default-sbml-template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinStrainLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strainlink', to='main.ProteinIdentifier')),
                ('strain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proteinlink', to='main.Strain')),
            ],
            options={
                'db_table': 'protein_strain',
            },
        ),
    ]
