# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:26
# flake8: noqa

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_unique_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneStrainLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'gene_strain',
            },
        ),
        migrations.RemoveField(
            model_name='geneidentifier',
            name='location_end',
        ),
        migrations.RemoveField(
            model_name='geneidentifier',
            name='location_in_genome',
        ),
        migrations.RemoveField(
            model_name='geneidentifier',
            name='location_start',
        ),
        migrations.RemoveField(
            model_name='geneidentifier',
            name='positive_strand',
        ),
        migrations.AddField(
            model_name='genestrainlink',
            name='gene',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strainlink', to='main.GeneIdentifier'),
        ),
        migrations.AddField(
            model_name='genestrainlink',
            name='strain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genelink', to='main.Strain'),
        ),
    ]
