# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20151209_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='object_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='main.EDDObject'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='object_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='main.EDDObject'),
        ),
        migrations.AlterField(
            model_name='study',
            name='object_ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='main.EDDObject'),
        ),
    ]
