# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add-gene-strain-link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='replicate',
        ),
    ]
