# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_measurement_meta_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinidentifier',
            name='length',
            field=models.IntegerField(blank=True, help_text='sequence length', null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='proteinidentifier',
            name='mass',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='of unprocessed protein, in Daltons', max_digits=16, null=True, verbose_name='Mass'),
        ),
        migrations.AddField(
            model_name='proteinidentifier',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Datasource'),
        ),
    ]
