# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 00:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_convert-b-number-to-uniprot'),
    ]

    operations = [
        migrations.AddField(
            model_name='metabolite',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=main.models.VarCharField(), default=[], size=None),
        ),
    ]
