# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 18:50
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Count

from main.models import Metabolite


def move_keywords(apps, schema_editor):
    OldMetabolite = apps.get_model('main', 'Metabolite')
    qs = OldMetabolite.objects.annotate(kcount=Count('keywords')).filter(kcount__gt=0)
    for m in qs.prefetch_related('keywords'):
        tags = [kw.name for kw in m.keywords.all()]
        Metabolite.objects.filter(pk=m.pk).update(tags=tags)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_metabolite_tags'),
    ]

    operations = [
        migrations.RunPython(move_keywords),
    ]
