# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_move-keywords-to-tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metabolitekeyword',
            name='mod_by',
        ),
        migrations.RemoveField(
            model_name='metabolite',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='MetaboliteKeyword',
        ),
    ]
