# Generated by Django 2.0.10 on 2019-01-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_study-pk-for-export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementtype',
            name='type_group',
            field=models.CharField(choices=[('_', 'Generic'), ('m', 'Metabolite'), ('g', 'Gene Identifier'), ('p', 'Protein Identifier'), ('h', 'Phosphor')], default='_', help_text='Class of data for this Measurement Type.', max_length=8, verbose_name='Type Group'),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='type_group',
            field=models.CharField(choices=[('_', 'Generic'), ('m', 'Metabolite'), ('g', 'Gene Identifier'), ('p', 'Protein Identifier'), ('h', 'Phosphor')], default='_', help_text='Type of measurement for which this unit is used.', max_length=8, verbose_name='Group'),
        ),
    ]
