# Generated by Django 2.0.10 on 2019-01-28 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("main", "0015_typo-fix")]

    operations = [
        migrations.AlterField(
            model_name="grouppermission",
            name="group",
            field=models.ForeignKey(
                help_text="Group this permission applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="auth.Group",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="userpermission",
            name="user",
            field=models.ForeignKey(
                help_text="User this permission applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
