# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove-metabolite-keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaboliteexchange',
            name='exchange_name',
            field=main.models.VarCharField(),
        ),
        migrations.AlterField(
            model_name='metaboliteexchange',
            name='measurement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MeasurementType'),
        ),
        migrations.AlterField(
            model_name='metaboliteexchange',
            name='reactant_name',
            field=main.models.VarCharField(),
        ),
        migrations.AlterField(
            model_name='metabolitespecies',
            name='measurement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.MeasurementType'),
        ),
        migrations.AlterField(
            model_name='metabolitespecies',
            name='species',
            field=main.models.VarCharField(),
        ),
        migrations.AlterUniqueTogether(
            name='metaboliteexchange',
            unique_together=set([('sbml_template', 'exchange_name'), ('sbml_template', 'reactant_name'), ('sbml_template', 'measurement_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='metabolitespecies',
            unique_together=set([('sbml_template', 'species'), ('sbml_template', 'measurement_type')]),
        ),
        migrations.AlterIndexTogether(
            name='metaboliteexchange',
            index_together=set([('sbml_template', 'exchange_name'), ('sbml_template', 'reactant_name')]),
        ),
        migrations.AlterIndexTogether(
            name='metabolitespecies',
            index_together=set([('sbml_template', 'species')]),
        ),
    ]
