# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 19:44
from __future__ import print_function, unicode_literals

import sys

from django.db import migrations


def parse_sbml_for_reactions(apps, schema_editor):
    # load directly, migration-derived model class does not have methods we need to use
    from main.models import SBMLTemplate
    # need to be able to convert to migration-derived classes
    Template = apps.get_model('main', 'SBMLTemplate')
    # these we can load from migration-derived classes
    MetaboliteExchange = apps.get_model('main', 'MetaboliteExchange')
    MetaboliteSpecies = apps.get_model('main', 'MetaboliteSpecies')
    for template in SBMLTemplate.objects.all():
        _template = Template.objects.get(pk=template.pk)
        try:
            doc = template.parseSBML()
            model = doc.getModel()
            for species in model.getListOfSpecies():
                (m_species, created) = MetaboliteSpecies.objects.get_or_create(
                    sbml_template=_template,
                    species=species.getId(),
                )
            for reaction in model.getListOfReactions():
                reactants = reaction.getListOfReactants()
                if len(reactants) == 1:
                    (m_exchange, created) = MetaboliteExchange.objects.get_or_create(
                        sbml_template=_template,
                        exchange_name=reaction.getId(),
                        reactant_name=reactants[0].getSpecies()
                    )
        except Exception as e:
            # capture any error loading template and move on to the next
            # don't care about specific error, no need to do any other recovery
            print('Encountered an error processing SBML template %s: %s' % (_template.name, e),
                  file=sys.stderr)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sbml-nullable-measurementtypes'),
    ]

    operations = [
        migrations.RunPython(parse_sbml_for_reactions),
    ]
