# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 00:42
from __future__ import unicode_literals

from django.db import migrations


def normalize_vector_measurements(apps, schema_editor):
    Measurement = apps.get_model('main', 'Measurement')
    MeasurementValue = apps.get_model('main', 'MeasurementValue')
    # Some vectors are not normalized to sum to 1
    values = MeasurementValue.objects.filter(y__len__gt=1)
    for v in values:
        total = sum(v.y)
        if round(total) > 1:
            v.y = map(lambda y: y / total, v.y)
    # Some "vectors" should not be vectors
    measures = Measurement.objects.filter(measurement_format='1', measurement_type__type_group='p')
    for m in measures.prefetch_related('measurementvalue_set'):
        vector = False
        for v in m.measurementvalue_set.all():
            if len(v.y) > 1:
                vector = True
        if not vector:
            m.measurement_format = '0'
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_parse-sbml-for-reactions'),
    ]

    operations = [
        migrations.RunPython(normalize_vector_measurements),
    ]
