# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_normalize_vector_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_format',
            field=models.CharField(choices=[('0', 'scalar'), ('1', 'vector'), ('2', 'histogram'), ('3', 'sigma')], default=0, max_length=2),
        ),
    ]
