# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160713_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryonePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('N', 'None'), ('R', 'Read'), ('W', 'Write')], default='N', max_length=8)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Study')),
            ],
            options={
                'db_table': 'study_public_permission',
            },
        ),
    ]
