# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-19 20:12
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.deletion import CASCADE


def move_source(apps, schema_editor):
    # could not get this to work with a direct update, so doing in a loop
    Metabolite = apps.get_model('main', 'Metabolite')
    for m in Metabolite.objects.exclude(source_id__isnull=True):
        m.type_source_id = m.source_id
        m.save()
    ProteinIdentifier = apps.get_model('main', 'ProteinIdentifier')
    for p in ProteinIdentifier.objects.exclude(source_id__isnull=True):
        p.type_source_id = p.source_id
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_fix_measurement_typegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtype',
            name='type_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=CASCADE, to='main.Datasource'),
        ),
        migrations.RunPython(move_source),
    ]
