# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-28 21:14
from __future__ import unicode_literals

import uuid

from django.db import migrations, models

from main import models as edd_models


def build_uuids(apps, schema_editor):
    EDDObject = apps.get_model('main', 'EDDObject')
    MeasurementType = apps.get_model('main', 'MeasurementType')
    MetadataType = apps.get_model('main', 'MetadataType')
    for item in EDDObject.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid', ])
    for item in MeasurementType.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid', ])
    for item in MetadataType.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid', ])


def build_slugs(apps, schema_editor):
    # apps.get_model does not know about special save code for Study
    for item in edd_models.Study.objects.all():
        item.save(force_update=True, update_fields=['slug', ])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_measurementtype_type_source'),
    ]

    operations = [
        # Create initial fields
        migrations.AddField(
            model_name='eddobject',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='measurementtype',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='metadatatype',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),

        # Assign random UUIDs to objects
        migrations.RunPython(build_uuids, reverse_code=migrations.RunPython.noop),
        # Assign slugs to Study objects
        migrations.RunPython(build_slugs, reverse_code=migrations.RunPython.noop),

        # Alter fields to be non-null, unique
        migrations.AlterField(
            model_name='eddobject',
            name='uuid',
            field=models.UUIDField(editable=False, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='uuid',
            field=models.UUIDField(editable=False, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='uuid',
            field=models.UUIDField(editable=False, null=False, unique=True),
        ),

        # PostgreSQL-specific bits here!
        # Django will attempt to assign a single UUID as default in migration, even with a
        #   callable. Instead, directly use Postgres support for UUID function.
        migrations.RunSQL(
            'ALTER TABLE "edd_object" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4();',
            'ALTER TABLE "edd_object" ALTER COLUMN "uuid" DROP DEFAULT;',
        ),
        migrations.RunSQL(
            'ALTER TABLE "measurement_type" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4();',
            'ALTER TABLE "measurement_type" ALTER COLUMN "uuid" DROP DEFAULT;',
        ),
        migrations.RunSQL(
            'ALTER TABLE "metadata_type" ALTER COLUMN "uuid" SET DEFAULT uuid_generate_v4();',
            'ALTER TABLE "metadata_type" ALTER COLUMN "uuid" DROP DEFAULT;',
        ),
    ]
