services:
  postgres:
    environment:
      POSTGRES_USER: postgres
    image: library/postgres:14
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 1m
    networks:
      - backnet
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./secrets/000_init.sql:/docker-entrypoint-initdb.d/000_init.sql
volumes:
  postgres_db: {}
