services:
  http:
    environment:
      CACHE_URL: rediscache://redis:6379/1
  redis:
    command:
      - redis-server
      - --appendonly
      - "yes"
    image: library/redis:6
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 1m
    networks:
      - backnet
    volumes:
      - redis_db:/data
  websocket:
    environment:
      CACHE_URL: rediscache://redis:6379/1
  worker:
    environment:
      CACHE_URL: rediscache://redis:6379/1
volumes:
  redis_db: {}
