"""Module contains exceptions for edd.load."""

from .core import (
    EDDImportError,
    EDDImportWarning,
    InvalidLoadRequestError,
    LoadError,
    ReportingLimitWarning,
)
from .execute import ExecutionError, ExecutionWarning, UnplannedOverwriteError
from .parse import (
    BadParserError,
    DuplicateColumnError,
    IgnoredColumnWarning,
    IgnoredValueWarning,
    IgnoredWorksheetWarning,
    InvalidValueError,
    ParseError,
    RequiredColumnError,
    RequiredValueError,
    UnsupportedMimeTypeError,
    UnsupportedUnitsError,
)
from .resolve import (
    CommunicationError,
    DuplicateAssayError,
    DuplicateLineError,
    IllegalTransitionError,
    ImportConflictWarning,
    ImportTooLargeError,
    MeasurementCollisionError,
    MergeWarning,
    MissingAssayTimeError,
    OverdeterminedTimeError,
    OverwriteWarning,
    ResolveError,
    ResolveWarning,
    TimeNotProvidedError,
    TimeUnresolvableError,
    UnmatchedAssayError,
    UnmatchedLineError,
    UnmatchedMtypeError,
    UnmatchedStudyInternalsError,
)
from .table import ImportBoundsError, ImportTaskError

__all__ = [
    "BadParserError",
    "CommunicationError",
    "DuplicateAssayError",
    "DuplicateColumnError",
    "DuplicateLineError",
    "EDDImportError",
    "EDDImportWarning",
    "ExecutionError",
    "ExecutionWarning",
    "IgnoredColumnWarning",
    "IgnoredValueWarning",
    "IgnoredWorksheetWarning",
    "IllegalTransitionError",
    "ImportBoundsError",
    "ImportConflictWarning",
    "ImportTaskError",
    "ImportTooLargeError",
    "InvalidLoadRequestError",
    "InvalidValueError",
    "LoadError",
    "MeasurementCollisionError",
    "MergeWarning",
    "MissingAssayTimeError",
    "OverdeterminedTimeError",
    "OverwriteWarning",
    "ParseError",
    "ReportingLimitWarning",
    "RequiredColumnError",
    "RequiredValueError",
    "ResolveError",
    "ResolveWarning",
    "TimeNotProvidedError",
    "TimeUnresolvableError",
    "UnmatchedAssayError",
    "UnmatchedLineError",
    "UnmatchedMtypeError",
    "UnmatchedStudyInternalsError",
    "UnplannedOverwriteError",
    "UnsupportedMimeTypeError",
    "UnsupportedUnitsError",
]
