services:
  postgres:
    environment:
      POSTGRES_DB: edd
      POSTGRES_USER: edduser
    image: library/postgres:11
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 1m
    networks:
      - backnet
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db: {}
