services:
  rabbitmq:
    environment:
      HOSTNAME: rabbitmq
      RABBITMQ_DEFAULT_USER: edduser
      RABBITMQ_DEFAULT_VHOST: edd
      RABBITMQ_NODENAME: rabbit@rabbitmq
    hostname: rabbitmq
    image: jbei/rabbitmq:3.7-management-alpine
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 1m
    networks:
      - backnet
