services:
  http:
    environment:
      SEARCH_URL: solr://solr:8983/solr/
  solr:
    image: jbei/solr:8
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 1m
    networks:
      - backnet
    volumes:
      - solr_home:/var/solr/data
  websocket:
    environment:
      SEARCH_URL: solr://solr:8983/solr/
  worker:
    environment:
      SEARCH_URL: solr://solr:8983/solr/
volumes:
  solr_home: {}
