---
version: '3.6'
networks:
  proxynet: {}
volumes:
  attachdata: {}
  staticdata: {}
  nginx_certs: {}
  nginx_confd: {}
  nginx_vhost: {}
  nginx_webroot: {}
services:
  nginx:
    build: ./nginx/
    image: jbei/nginx:mainline
    # using container_name means there will only ever be one nginx container!
    container_name: nginx
    restart: always
    networks:
      - proxynet
    volumes:
      - nginx_confd:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_webroot:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - attachdata:/usr/share/nginx/html/uploads:ro
      - staticdata:/usr/share/nginx/html/static:ro
    healthcheck:
      test: ['CMD', '/healthcheck.sh']
      interval: 1m
      timeout: 5s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: 1m
        max-file: '5'
    # Below are some options for exposing HTTP/HTTPS ports from nginx to outside the container
    ports:
      # Make the http/https ports available on the Docker host IPv4 loopback interface
      - '127.0.0.1:80:80'
      - '127.0.0.1:443:443'
      # Make the http/https ports available on ALL Docker host IPv4 interfaces
      #- '0.0.0.0:80:80'
      #- '0.0.0.0:443:443'
      # Make the http/https ports available on a private IP like 10.20.17.100
      #- '10.20.17.100:80:80'
      #- '10.20.17.100:443:443'
  nginx-gen:
    build: ./nginx-gen/
    image: jbei/nginx-gen:latest
    # using container_name means there will only ever be one nginx-gen container!
    container_name: nginx-gen
    entrypoint:
      - '/usr/local/bin/docker-gen'
      - '-watch'
      - '-notify-sighup'
      - 'nginx'
      - '-wait'
      - '5s:30s'
      - '/etc/docker-gen/templates/nginx.tmpl'
      - '/etc/nginx/conf.d/default.conf'
    networks:
      - proxynet
    volumes:
      - nginx_confd:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_webroot:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: 'json-file'
      options:
        max-size: 1m
        max-file: '5'
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    depends_on:
      - nginx
    networks:
      - proxynet
    volumes:
      - nginx_confd:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_webroot:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
    logging:
      driver: 'json-file'
      options:
        max-size: 1m
        max-file: '5'
